# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: 'test', project_dir: 'android')
  end

  desc "Build apk"
  lane :build do |options|
    gradle(task: 'assemble', build_type: options[:build_type], project_dir: 'android')
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy to firebase app distribution"
  lane :firebase_distribution do
    firebase_app_distribution(
      apk_path: sh("pwd | tr -d '\n'").concat("/../android/app/build/outputs/apk/debug/app-debug.apk"), 
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      release_notes: "First Alpha Release",
    )
  end
end
