name: Build APK, execute Regression Test and Publish

on:
  pull_request: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install firebase tools
      run: |
        yarn global add firebase-tools
        echo "::add-path::$(yarn global bin)"

    - name: Setup fastlane
      run: bundle install

# TODO: Auto increment build numbers

    - name: Build APK
      run: bundle exec fastlane build

# TODO: Verify if firebase distribution is able to find APK
# TODO: Setup secrets in Github Actions
# TODO: Execute Regression Tests

    - name: Distribute to Firebase
      run: bundle exec fastlane android firebase_distribution
      env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} 
