name: Build APK, execute Regression Test and Publish

on:
  pull_request:
    branches:
    - main

jobs:
  build_verify_distribute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Install firebase tools
      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH
        echo "$(yarn global bin)"
        echo "$PATH"

    - name: Setup fastlane
      run: |
        gem install bundler
        bundle install

# TODO: Auto increment build numbers

    - name: Build APK
      run: bundle exec fastlane build

# TODO: Verify if firebase distribution is able to find APK
# TODO: Setup secrets in Github Actions
# TODO: Execute Regression Tests

    - name: Distribute to Firebase
      run: bundle exec fastlane android firebase_distribution
      env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} 
