name: Appium CI

on:
  pull_request:
    branches:
    - main

jobs:
  emulator_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install and Run Appium Server
      run: |
        chmod +x ./InstallAndRunAppiumServer.sh # install and run appium server in the background
        ./InstallAndRunAppiumServer.sh

    - name: Download AVD and Start Emulator
      run: |
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-28;google_apis;x86_64'
        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test_device -k 'system-images;android-28;google_apis;x86_64' --force
        echo $ANDROID_HOME/emulator/emulator -list-avds
        echo "Booting Emulators"
        nohup $ANDROID_HOME/emulator/emulator -avd test_device -no-snapshot > /dev/null 2>&1 &
        $ANDROID_HOME/platform-tools/adb -s emulator-5554 wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
    
    - name: Check Android Emulator
      run: |
        echo "Running Emulator"
        $ANDROID_HOME/platform-tools/adb devices
        echo "Emulator started"
